### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by melanger**

### CODE REVIEW

**Comment by melanger** [comment]
@restena-sw Hi, I am not able to satisfy the dependency checker, even when I add modules ldap and radius to composer.json, it still complains:

```
ComposerRequireChecker 4.6.0@a5d4951d0839b57fb5dce1d6d0a6e36f23b2823f
The following 2 unknown symbols were found:
+---------------------------------------------+--------------------+
| Unknown Symbol                              | Guessed Dependency |
+---------------------------------------------+--------------------+
| SimpleSAML\Module\ldap\Auth\Source\Ldap     |                    |
| SimpleSAML\Module\radius\Auth\Source\Radius |                    |
+---------------------------------------------+--------------------+
```

**Comment by tvdijen** [comment]
We are aware of this and we have a fix pending

**Comment by restena-sw** [comment]
Sorry, was on holiday. There is not actually any hard dependency on RADIUS nor LDAP, so these modules should not be listed in composer.json.
I will implement the fix that removes the literal mention of these classes with a class alias name, and then remove the dependency.

**Comment by restena-sw** [comment]
Pushed.

**Pull request merged**
