### PR TITLE
Fix Psalm-issues

### PR DESCRIPTION
**Pull request by tvdijen**

### CODE REVIEW

**Comment by tvdijen** [comment]
Good catch!

**Comment by restena-sw** [comment]
So is it okay if the min PHP version for this module is now 7.1 due to the syntax I talked about earlier? If so, I think this PR is ready to merge (and I would make a 1.0 release afterwards as there are no open bugs then).

**Comment by tvdijen** [comment]
Ah, I missed that comment, sorry!
I didn't push the version in this PR.. It's because `spomky-labs/cbor-php` requires PHP 7.1..

> Would the introduced change mean that people deploying the module are forced into a much newer PHP version just because of the module?
Yes, that's the consequence.. SSP is pushing to 7.0 for 1.19 and 7.2 for 2.0, so I think it shouldn't matter that much..

**Comment by restena-sw** [comment]
Great, merged.

**Pull request merged**
