### PR TITLE
Add Controllers + Controller-tests

### LINKED ISSUE #14: Create controllers for all the scripts in www/
The new routing mechanism allows us to implement MVC, which is great for unit testing. We should move the functionality implemented in the scripts in [www](https://github.com/simplesamlphp/simplesamlphp-module-webauthn/tree/master/www) and move it to controller classes, then have routes for those controllers.

Since we still need to support the old user interface, we still need to have those scripts in `www` around, but those could just call the corresponding method from a controller class.

### PR DESCRIPTION
**Pull request by tvdijen**
Closes #14

### CODE REVIEW

**Comment by restena-sw** [comment]
I see that the commits to the PR are slowing down. Do you think this is now ready for merging, or are you still working on it?

**Comment by tvdijen** [comment]
Hi Stefan!
This is as good as it gets with the unit tests without a lot of refactoring.. I could use a tester though!

**Comment by restena-sw** [comment]
Hm. Since this is a rather complex change, and the code as it is pre-PR is known working and tested, how about the following:

- tag a 1.0 release with the current state (PR not merged)
- merge and test @dev
- make the post-merge version 1.1

?

**Comment by tvdijen** [comment]
Works for me!

**Comment by restena-sw** [comment]
I tested current master (including the code from this PR). It worked quite well: both basic login and the key management page worked as expected.
I think we can consider this good enough.

**Comment by tvdijen** [comment]
Thanks, it's good to hear that hard work pays off! It's ready for SSP 2.0 now

**Pull request merged**
